spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FullStackMania/CloudConfiguration
          search-paths:
           - '{application}'
          refresh-rate: 0
        default-label: main
      

server:
  port: 8081
